linters:
  fast: false
  enable-all: true
  disable:
    - bodyclose
    - dupl
    - gochecknoglobals
    - gosec
    - lll
    - wsl
    - depguard
    - testpackage
    - exhaustruct
    - tagliatelle
    # Disbale deprecated linters
    - interfacer
    - ifshort
    - structcheck
    - maligned
    - scopelint 
    - deadcode
    - nosnakecase
    - golint
    - varcheck
    - exhaustivestruct